"""add foreign key to student

Revision ID: 63c72b48d240
Revises: cf3301233727
Create Date: 2025-09-21 22:59:03.059391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c72b48d240'
down_revision = 'cf3301233727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_member_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'member', ['created_by_member_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by_member_id')

    # ### end Alembic commands ###
